/*
 * Klarna Checkout API V3
 * The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PickupLocationV1;
import com.konfigthis.client.model.ProductV1;
import com.konfigthis.client.model.TimeslotV1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeliveryDetailsV1
 */
public class DeliveryDetailsV1Test {
    private final DeliveryDetailsV1 model = new DeliveryDetailsV1();

    /**
     * Model tests for DeliveryDetailsV1
     */
    @Test
    public void testDeliveryDetailsV1() {
        // TODO: test DeliveryDetailsV1
    }

    /**
     * Test the property 'carrier'
     */
    @Test
    public void carrierTest() {
        // TODO: test carrier
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'timeslot'
     */
    @Test
    public void timeslotTest() {
        // TODO: test timeslot
    }

    /**
     * Test the property 'pickupLocation'
     */
    @Test
    public void pickupLocationTest() {
        // TODO: test pickupLocation
    }

}
