/*
 * Klarna Checkout API V3
 * The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MerchantRequestedCheckbox;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MerchantRequested
 */
public class MerchantRequestedTest {
    private final MerchantRequested model = new MerchantRequested();

    /**
     * Model tests for MerchantRequested
     */
    @Test
    public void testMerchantRequested() {
        // TODO: test MerchantRequested
    }

    /**
     * Test the property 'additionalCheckbox'
     */
    @Test
    public void additionalCheckboxTest() {
        // TODO: test additionalCheckbox
    }

    /**
     * Test the property 'additionalCheckboxes'
     */
    @Test
    public void additionalCheckboxesTest() {
        // TODO: test additionalCheckboxes
    }

}
