/*
 * Klarna Checkout API V3
 * The checkout API is used to create a checkout with Klarna and update the checkout order during the purchase. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).\\n\\nRead more on [Klarna checkout](https://docs.klarna.com/klarna-checkout/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProductIdentifiers;
import com.konfigthis.client.model.ShippingAttributes;
import com.konfigthis.client.model.Subscription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderLine
 */
public class OrderLineTest {
    private final OrderLine model = new OrderLine();

    /**
     * Model tests for OrderLine
     */
    @Test
    public void testOrderLine() {
        // TODO: test OrderLine
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'subscription'
     */
    @Test
    public void subscriptionTest() {
        // TODO: test subscription
    }

    /**
     * Test the property 'quantityUnit'
     */
    @Test
    public void quantityUnitTest() {
        // TODO: test quantityUnit
    }

    /**
     * Test the property 'unitPrice'
     */
    @Test
    public void unitPriceTest() {
        // TODO: test unitPrice
    }

    /**
     * Test the property 'taxRate'
     */
    @Test
    public void taxRateTest() {
        // TODO: test taxRate
    }

    /**
     * Test the property 'totalAmount'
     */
    @Test
    public void totalAmountTest() {
        // TODO: test totalAmount
    }

    /**
     * Test the property 'totalDiscountAmount'
     */
    @Test
    public void totalDiscountAmountTest() {
        // TODO: test totalDiscountAmount
    }

    /**
     * Test the property 'totalTaxAmount'
     */
    @Test
    public void totalTaxAmountTest() {
        // TODO: test totalTaxAmount
    }

    /**
     * Test the property 'merchantData'
     */
    @Test
    public void merchantDataTest() {
        // TODO: test merchantData
    }

    /**
     * Test the property 'productUrl'
     */
    @Test
    public void productUrlTest() {
        // TODO: test productUrl
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'productIdentifiers'
     */
    @Test
    public void productIdentifiersTest() {
        // TODO: test productIdentifiers
    }

    /**
     * Test the property 'shippingAttributes'
     */
    @Test
    public void shippingAttributesTest() {
        // TODO: test shippingAttributes
    }

}
